=== command
CI="true" GITHUB_ACTIONS="true" GITHUB_EVENT_NAME="pull_request" GITHUB_REPOSITORY="project_name/project_name" GITHUB_RUN_ID="35" GITHUB_ACTOR="some_test_username" GITHUB_REF="some/branch-name" GITHUB_EVENT_PATH="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --debug --no-force-color
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain

=== end of stdout - plain

=== stderr - plain
Scan environment:
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment github-actions, triggering event is pull_request
  semgrep.dev - authenticated as org_name

head branch (bar) has latest commit 17b3114fb3d41437abc2a3e6499db84ad921e6f0, fetching that commit now.
Trying to shallow fetch branch foo from origin
base branch (foo) has latest commit f7ee3123ed098941662685dd8b726fceee48f78d
Fixing git state for github action pull request
Calling git rev-parse HEAD
stashed_rev: 17b3114fb3d41437abc2a3e6499db84ad921e6f0
Not on head ref: 17b3114fb3d41437abc2a3e6499db84ad921e6f0; checking that out now.
Attempting to find merge base, attempt_count=0, fetch_depth=0
Returning to original head revision 17b3114fb3d41437abc2a3e6499db84ad921e6f0
Command failed with exit code: 1
-----
Command failed with output:


Failed to run 'git merge-base f7ee3123ed098941662685dd8b726fceee48f78d 17b3114fb3d41437abc2a3e6499db84ad921e6f0'. Possible reasons:

- the git binary is not available
- the current working directory is not a git repository
- the current working directory is not marked as safe
    (fix with `git config --global --add safe.directory $(pwd)`)

Try running the command yourself to debug the issue.
Not sending pseudonymous metrics since metrics are configured to OFF and registry usage is False

=== end of stderr - plain